### ISSUE TITLE
Start indexing homepage and sub-pages (not just blog articles)

### ISSUE THREAD

**Issue by etagwerker** [fastruby/librarian#21]
## Current 

Right now we are indexing only blog articles via the blog's sitemap.

## Expected

We want to expand the reach of the indexing mechanism to include all pages (not just blog) 

## Biz Goal

That way we can later quickly generate shareable links to homepage and internal pages.

**Comment by fbuys** [comment]
I have submitted a PR over here: https://github.com/fastruby/librarian/pull/27

**Comment by etagwerker** [comment]
Closed by #27
