### ISSUE TITLE
Add a button to run the sitemap reader job

### ISSUE THREAD

**Issue by FionaDL** [fastruby/librarian#22]
Current
Currently, after publishing a blog post you have to wait for the scheduler to run the `rake read` task to read the sitemap for our sites. Usually I need an immediate libraraian link after publishing and I have to run the rake task from heroku. 

Expected
Anyone should be able to push a button to run the task on the site.

**Comment by etagwerker** [comment]
@FionaDL I updated the schedule for the job to run every 10 minutes. So this feature is low priority for now.
