### ISSUE TITLE
Social media snippets interface looks broken

### ISSUE THREAD

**Issue by etagwerker** [fastruby/librarian#24]
## Current

When reading social media snippets, the UI looks broken. 

## Expected

When reading social media snippets, the UI should look not broken

## Screenshot

<img width="1336" alt="Screen Shot 2023-07-23 at 5 54 00 PM" src="https://github.com/fastruby/librarian/assets/17584/0d9120f9-dba3-4bdb-8e83-2b99d3cf1c32">

**Comment by rishijain** [comment]
Hey @etagwerker ,
I need to confirm the problem and the acceptance criteria for it:

The broken part is the black background we see on the attached screenshot.

The correct behaviour is there should not be any black background on the screen. I have attached a screenshot of what I mean by no black background.
<img width="1311" alt="Screenshot 2023-10-10 at 4 35 15 PM" src="https://github.com/fastruby/librarian/assets/946527/35e9d30d-8580-4d50-a24d-32bd5d1158ff">

**Comment by etagwerker** [comment]
@rishijain Yes, that looks much better. Could you please improve the textareas so that they don't have that much white space after the text?

**Comment by etagwerker** [comment]
Closed by https://github.com/fastruby/librarian/pull/31
