### ISSUE TITLE
Add link filtering and searching

### ISSUE THREAD

**Issue by fbuys** [fastruby/librarian#30]
Right now, you need to look through all the links or make use of the browser's search functionality to find a specific link.

After we decided to index all links (not just the blog links) it became a lot more obvious that we might need to add search and/or filtering to the links list.
See: https://github.com/fastruby/librarian/pull/27/files

The Search box (and filter options) could be below the main navigation.

<img width="1339" alt="image" src="https://github.com/fastruby/librarian/assets/3785596/aa63396d-004d-4315-859d-ab55c0624460">

Perhaps we could start with simple text search.
And only one filter that could toggle between blog links and other links. (blog links (usually) have a publish_at date and others links don't)

**Comment by etagwerker** [comment]
@fbuys Thanks for thinking of this! 

I don't think this is a big issue. Right now the browser search feature is enough. 

I've been using librarian quite a bit recently and I don't think this is necessary.
